fixed hero alignment
unswwit/emp-website pull request #83
Opened 2024-03-30 16:12 UTC by sarexakrish13

Ticket 179 
Fixed hero alignment by editing in file Home.module.css

2024-03-30 16:17 UTC, ItsLame requested changes
also, probably change the PR name to `fix(frontend): fix hero alignment [wit-179]`

2024-03-30 16:40 UTC, ItsLame requested changes

2024-03-30 16:40 UTC, ItsLame commented on frontend/styles/Home.module.css
> +
keep the gap

2024-03-30 16:45 UTC, ItsLame requested changes
i think this is the left padding which we want to keep

2024-03-30 16:45 UTC, ItsLame commented on frontend/styles/Home.module.css
> +  padding: 0rem 0rem 0rem 0rem;
add padding back

2024-03-31 05:35 UTC, ItsLame commented on frontend/styles/Home.module.css
> +    padding: 0rem 0rem 0rem 10rem;
adding more padding to the left is not needed

2024-03-31 05:35 UTC, ItsLame commented on frontend/styles/Home.module.css
> +    gap: 10em;
this can be changed to something more responsive (if you set width to like 2000/3000px++ you can still see the space).

2024-03-31 05:37 UTC, ItsLame requested changes
still some spacing issues

2024-03-31 06:13 UTC, sarexakrish13 commented
I adjusted the media too 1100 and removed the padding at the bottom when the shrinks and also when it expands i adjusted so its at flex-end

2024-03-31 06:29 UTC, ItsLame commented on frontend/styles/Home.module.css
> +  @media screen and (max-width: 1100px) {
add new line before this (white space; helps with readability)

2024-03-31 06:29 UTC, ItsLame commented on frontend/styles/Home.module.css
> +    padding: 7rem 2rem 0rem 2rem;
we don't need to change this for now

2024-03-31 06:29 UTC, ItsLame commented on frontend/styles/Home.module.css
> +
delete empty line

2024-03-31 06:30 UTC, ItsLame commented on frontend/styles/Home.module.css
> +  @media screen and (min-width: 1700px) {
add new line before this (white space; helps with readability)

2024-03-31 06:30 UTC, ItsLame commented on frontend/styles/Home.module.css
> +    gap: 15em;
i think you can remove this

2024-03-31 06:31 UTC, ItsLame commented on frontend/styles/Home.module.css
> +    justify-content: flex-end;
try `space-between` instead

2024-03-31 06:31 UTC, ItsLame requested changes
Few more changes

2024-03-31 06:37 UTC, ItsLame approved these changes

2024-03-31 08:12 UTC, merged